language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - "~/.platformio"
install:
- pip install -U platformio
- platformio platform install espressif8266 --with-package tool-mkspiffs
script:
- platformio --version
- platformio run -e io2life_deploy
- platformio run -t buildfs -e io2life_deploy
deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  api_key:
     #secure: "ARSwLJV3FD/aYU1NAE2m148TFairEtn94M2GoPT3t6O7K3Bhfbx/k0KxLWwJW1DuCk5/lftsi5Wpr4g4qNSU5D2JxYKPoRRRDE1kd6OKhuyitTrNmrvKD2jLfa37hCXxpK6GD1G5zZgFiB5A75OdF2v8dBdSf7puMMgG/xiEqzjUwPEzApM1GY8c1sT0pZJlQL7ex6PeLz0aV4mCBdFhuwRmY8k7XnFbRl/0xvAN+XBwWeVynd5GnyIE0LhCftng1S2371yPBIjHeGCCCJOpwhchooTdRio0ZCAWgldfobhB+D01ZA3Ke6zEFjgwRXSTKZyi09GPaM7NQzPr1JkfpBEPLSB565CDfz4aeqfrzorOUA2fsEfT77bRTd3KHVIiv04cApROfScnrufYjSTOJBIhfu/1mXXOO0z3kH95xYrMxOQVgT1Q0Sg8t3SqG93Cyz+84ab1iW8UdFpI5eXJC1mPD0W77802HwU5ShYjeQsHrLUoN0tRk0HXxTDvq3srP98ucMFbkb4C1BQsCmQD7sxuaT/ZcioOVjxFk2Q4GI+EWrd8/ovTTZ+2lnIKng3a9TFIJX6FhwAkPPv6x5ohFxhHOkxPooZKSRQdQKP1WfVWQuiaYNN+gc6waJNLVGKcokDDWpf0nLpzAYilPDNwl9xSF68JJGjiAiuIAHGYRz0="
      secure: "d5Nu78Mj2kf+bTAhItVn4DJZhrDnghDSHN1rHw6KmHl1LsBLASaUdLmlJA6ozcye6PXAGuhB3HIMB0hlti8o1IAdwkqac1XzbBouhgun9Z9PW7NahpJrwOA0cGxhmklQ2ImNPQ2BZ4sX/dcZ1HibbsiqrfTVMsnNBhoIx375Z6HMpwChC+9CUXay40tv5HJXwi32ZttiKJAB95pJgptiq82/w/ZwA6Kc9qmH/jzCc5Kf2jc9N7iHL+m0KV7DkxoFtNsUy1cCHft6HPc3YCHj2xwNjzCEH3eSvT9KhoR4vSD13NDIJtGRMOQGxYubOHyc4INHGhvKK9ykcaWkR8u3W3LeWf+GNvAj6bcwbNBuFQPy7cleVpGkRjmYmpsAK1V6lMw/V9E+zfVrgBwDiRNgsgJYQQFgYrfoq+v92R7hWfCIjIMXh+9sphQPrWs1x9geUrUQvVtS5LUfMSAuWfnR2l+M0Q58WRYiD9NJQIUfOwwWT7OrKYQshC8wi/cQk/XL3LFZX25kjqfAKTQbK22fS8peg/+VzJXAaBV4VXkbPfTaqG9EDafKgFGUOx7/mNjcK5Zb0m3WsLt7wJHhYiuTxrL9Bl9ec6cDSjRdwIfKcUA/hKCHExP8FYfx+2tyXT2j232RfEaeo0yc+BPoWNpQeCo5mF4zMWOOLfAYkIH7q98="
  file:
  - ".pioenvs/io2life_deploy/firmware.bin"
  - ".pioenvs/io2life_deploy/spiffs.bin"
  on:
    repo: yileekorea/ESP-main
    all_branches: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$
