language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - "~/.platformio"
install:
- pip install -U platformio
- platformio platform install espressif8266 --with-package tool-mkspiffs
script:
- platformio --version
- platformio run -e io2life_deploy
- platformio run -t buildfs -e io2life_deploy

deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  api_key:
    secure: V+v043vfnPRZyManGG+D0UwwIoS5/WMucKAHvt29PPUsV/BDVWo9Kr4OOjgL6PPmJBu$
  file: firmware.bin
  on:
    repo: yileekorea/ESP-main
    branch: ''
    #condition: "$TRAVIS_TAG =~ ^[0-9]+\\.[0-9]+\\.[0-9]+$"
