language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - "~/.platformio"
install:
- pip install -U platformio
- platformio platform install espressif8266 --with-package tool-mkspiffs
script:
- platformio --version
- platformio run -e io2life_deploy
- platformio run -t buildfs -e io2life_deploy
deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  file:
  - ".pioenvs/io2life_deploy/firmware.bin"
  - ".pioenvs/io2life_deploy/spiffs.bin"
  on:
    repo: yileekorea/ESP-main
    all_branches: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$
    #condition: $BUILD_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$
  api-key:
    secure: QxqlOYNNmTyGDVea6uUZ1Sf/GK+X3FmsWVVHwEXughkhDBUEaqvZMyB5MHd5TX+UQU1BpCFNoGzF2vEPfDlSRkhxAz1F5UL5IrfK0aqJC/Goj3/Ssw91KYW19vXsLP9ogsMhJ/ZD0v8Zlrj+BrhpbhdzZAQwpCVqkAJll7QRGNtI7p+b51gZhh4R315MuYGvwRFgCwc/TpDWNkLDl0qY+kiAzcGswXWKbozmeFCvU39wrnWHFtRx5Y5NtGpGSG157m9m6fnWEJgHSq3rRQx3WyjzQEShxPOp2oDZugsaVqUe3XKx13Sbd0pA5okcoyh9y+ky6SLfVwnIfic5monhb0oZNXx7orW+BrJLItLORS3MtDkAD/SjZEPA44KuaEuuGKLW93Pg9ZEq4hsw5WRVx3Yub5Pn9n6dp1h8Y+54gxsx1iu4uzBWtPH2V/GLrcWigMzB96YRWNaon1wFOL5T3rovn9IutmjmeldempwM+awwGIonFvRSx6ozWXNTUQ8TTWoClnb+tgBQfH9/kKJ/Jg4OK5Tj95Ryh7s6kZwozHoNPiz4UZ53J/siSYA9WTXj7ir1MqvqMGcwXY77Mzfvzw3+irz/esv6x3h3SCqCWrxGZMpXi6yJOcvY/Sk47XorwDevq8RRjbkywtRLA/fAnZlXgrNvOgo+PPgIjcgLVK4=
